[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lango"
version = "0.1.0"
description = "Implementation of the programming language SystemO as described in 'A Second Look at Overloading' by Martin Odersky, Philip Wadler, and Martin Wehr in 1995."
readme = "README.md"
authors = [ {name = "Anton Kesy", email = "antonkesy@gmail.com"} ]
requires-python = ">=3.13"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
license = {text = "MIT license"}
dependencies = [
  "typer==0.16.0",
  "lark==1.2.2",
  "rich>=13",
]

[project.optional-dependencies]
dev = [
  "pytest==8.3.3",
  "coverage==7.10.2",
  "mypy==1.17.1",
]

[project.urls]
bugs = "https://github.com/antonkesy/lang-o/issues"
homepage = "https://github.com/antonkesy/lang-o"

[project.scripts]
lango = "lango.cli:main"

[tool.setuptools.packages.find]
include = ["lango*"]
namespaces = true

[tool.setuptools.package-data]
"*" = ["*.lark", "*.minio", "*.syso", "*.go"]
